// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH8l4EX-soFY5CPcUMfAWSLJEH7F3SK2A',
    appId: '1:227800710337:web:148c5e81e03bdab4d9e840',
    messagingSenderId: '227800710337',
    projectId: 'chatea-c9190',
    authDomain: 'chatea-c9190.firebaseapp.com',
    storageBucket: 'chatea-c9190.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVir8wGqxIXUotKn-smRY17oRvlvjQJL0',
    appId: '1:227800710337:android:4f08828dd3d80696d9e840',
    messagingSenderId: '227800710337',
    projectId: 'chatea-c9190',
    storageBucket: 'chatea-c9190.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJPtC74gyUqYKA6TENXHAgq4MHazuyq4I',
    appId: '1:227800710337:ios:36ff226eedd97f77d9e840',
    messagingSenderId: '227800710337',
    projectId: 'chatea-c9190',
    storageBucket: 'chatea-c9190.appspot.com',
    iosClientId: '227800710337-hp3f0f63rfq0j7vo6ojpv6eblepqgubo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chateaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJPtC74gyUqYKA6TENXHAgq4MHazuyq4I',
    appId: '1:227800710337:ios:36ff226eedd97f77d9e840',
    messagingSenderId: '227800710337',
    projectId: 'chatea-c9190',
    storageBucket: 'chatea-c9190.appspot.com',
    iosClientId: '227800710337-hp3f0f63rfq0j7vo6ojpv6eblepqgubo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chateaApp',
  );
}
